# Phase 6 — Ansible Inventory
# For local development/demo, we target localhost
[webservers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[dbservers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[all:vars]
app_name=complaint-management-system
app_port=5000
db_name=complaintsdb
db_user=admin
db_password=admin123
